// Note: terminating "/" or port number is mandatory
export const validMessageDomains = [
    "https://js.stripe.com/",
    "https://apps-services.screencloudapp.com/",
    "https://apps-backends-production.screen.cloud/",
    "https://apps-services.staging.screencloudapp.com/",
    "https://apps-backends-staging.screen.cloud/",
    "https://screencloud-testing.auth0.com/",
    "https://authenticate.next.sc/",
    "https://studio.dev.next.sc:3000",
    "https://studio.dev.next.sc/",
    "https://studio.edge.next.sc/",
    "https://studio.staging.next.sc/",
    "https://studio.screencloud.com/",
    "https://mc.dev.next.sc:3001",
    "https://mc.dev.next.sc/",
    "https://mc.edge.next.sc/",
    "https://mc.staging.next.sc/",
    "https://mc.screencloud.com/",
];
